volumes:
  data:

services:
  database:
    container_name: gameforge-db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: gameforge
      MYSQL_USER: gameforge
      MYSQL_PASSWORD: gameforge
      MYSQL_ROOT_PASSWORD: gameforge
    volumes:
      - data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - 3306:3306
    networks:
      - res

networks:
  res: