volumes:
  data:

services:
  database:
    image:  mysql/mysql-server:5.6
    container_name: gameforge-db
    environment:
      MYSQL_DATABASE: gameforge
      MYSQL_USER: gameforge
      MYSQL_PASSWORD: gameforge
      MYSQL_ROOT_PASSWORD: gameforge
      MYSQL_ROOT_HOST: "%"
    expose:
      - "3306"
    ports:
      - 3306:3306