services:

  database:
    container_name: gameforge-db
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: gameforge
      MARIADB_PASSWORD: gameforge
      MARIADB_ROOT_PASSWORD: gameforge
    expose:
      - "3306"
    ports:
      - 3306:3306
    networks:
      - res

networks:
  res: