services:

  database:
    container_name: gameforge-db
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: gameforge
      MARIADB_PASSWORD: gameforge
      MARIADB_ROOT_PASSWORD: gameforge
    expose:
      - "3306"
    networks:
      - res

  api:
    container_name: gameforge-api
    restart: always
    environment:
      MARIADB_USER: gameforge
      MARIADB_PASSWORD: gameforge
      MARIADB_ROOT_PASSWORD: gameforge
      DATABASE_URL: 'localhost:3306/gameforge'
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - res

networks:
  res: